#!/usr/bin/env uv run
# /// script
# requires-python = ">=3.12"
# dependencies = [
#   "matplotlib>=3.8",
#   "numpy>=1.26",
# ]
# ///
"""Generate boundary analysis figure for HHC stability paper.

Reads boundary_figure_data.json generated by report.py and creates a
two-panel figure showing:
- Left: Churn rate vs distance from boundary (baseline vs HHC)
- Right: Curvature vs distance from boundary (baseline vs HHC)

Usage:
    uv run scripts/generate_boundary_figure.py
    uv run scripts/generate_boundary_figure.py --input path/to/boundary_figure_data.json
    uv run scripts/generate_boundary_figure.py --output paper/figures/boundary_analysis.pdf
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


def load_figure_data(input_path: Path) -> dict:
    """Load boundary figure data from JSON file.

    Args:
        input_path: Path to boundary_figure_data.json

    Returns:
        Dictionary with figure data

    Raises:
        FileNotFoundError: If input file does not exist
        json.JSONDecodeError: If input file is not valid JSON
    """
    with open(input_path) as f:
        return json.load(f)


def create_boundary_figure(
    data: dict,
    output_path: Path,
    dpi: int = 300,
) -> None:
    """Create boundary analysis figure with two subplots.

    Args:
        data: Figure data dictionary from boundary_figure_data.json
        output_path: Path to save the output PDF
        dpi: Resolution for raster elements (default 300)
    """
    # Extract data
    distance_bins = np.array(data.get("distance_bins", [0, 16, 32, 64, 128, 256]))

    baseline = data.get("baseline", {})
    hhc = data.get("hhc", {})

    baseline_churn = np.array(baseline.get("churn_by_distance", [0] * len(distance_bins)))
    baseline_curvature = np.array(baseline.get("curvature_by_distance", [0] * len(distance_bins)))

    hhc_churn = np.array(hhc.get("churn_by_distance", [0] * len(distance_bins)))
    hhc_curvature = np.array(hhc.get("curvature_by_distance", [0] * len(distance_bins)))

    # Set up figure with two subplots
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))

    # Style settings
    baseline_style = {
        "color": "#1f77b4",
        "linestyle": "--",
        "marker": "o",
        "markersize": 6,
        "linewidth": 1.5,
        "label": "Baseline",
    }
    hhc_style = {
        "color": "#ff7f0e",
        "linestyle": "-",
        "marker": "s",
        "markersize": 6,
        "linewidth": 2,
        "label": "HHC",
    }

    # Left subplot: Token churn rate
    ax1.plot(distance_bins, baseline_churn, **baseline_style)
    ax1.plot(distance_bins, hhc_churn, **hhc_style)

    ax1.set_xlabel("Distance from boundary (bytes)", fontsize=11)
    ax1.set_ylabel("Token churn rate", fontsize=11)
    ax1.set_title("(a) Token Churn vs Distance", fontsize=12)
    ax1.legend(loc="upper right", frameon=True, framealpha=0.9)
    ax1.grid(True, alpha=0.3, linestyle="-", linewidth=0.5)
    ax1.set_xlim(left=-5)

    # Set y-axis limits with some padding
    churn_max = max(baseline_churn.max(), hhc_churn.max())
    churn_min = min(baseline_churn.min(), hhc_churn.min())
    churn_range = churn_max - churn_min if churn_max > churn_min else 0.1
    ax1.set_ylim(bottom=max(0, churn_min - 0.1 * churn_range), top=churn_max + 0.1 * churn_range)

    # Right subplot: Curvature
    ax2.plot(distance_bins, baseline_curvature, **baseline_style)
    ax2.plot(distance_bins, hhc_curvature, **hhc_style)

    ax2.set_xlabel("Distance from boundary (bytes)", fontsize=11)
    ax2.set_ylabel("Curvature", fontsize=11)
    ax2.set_title("(b) Curvature vs Distance", fontsize=12)
    ax2.legend(loc="upper right", frameon=True, framealpha=0.9)
    ax2.grid(True, alpha=0.3, linestyle="-", linewidth=0.5)
    ax2.set_xlim(left=-5)

    # Set y-axis limits with some padding
    curv_max = max(baseline_curvature.max(), hhc_curvature.max())
    curv_min = min(baseline_curvature.min(), hhc_curvature.min())
    curv_range = curv_max - curv_min if curv_max > curv_min else 0.1
    ax2.set_ylim(bottom=max(0, curv_min - 0.1 * curv_range), top=curv_max + 0.1 * curv_range)

    # Adjust layout
    plt.tight_layout()

    # Save figure
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=dpi, bbox_inches="tight", format="pdf")
    plt.close(fig)

    print(f"Figure saved to {output_path}")


def create_simulated_figure(output_path: Path) -> None:
    """Create a figure with simulated data for illustration.

    Args:
        output_path: Path to save the PDF
    """
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))

    # Placeholder data
    distance_bins = np.array([0, 16, 32, 64, 128, 256])

    # Simulated baseline data (higher churn/curvature at boundaries)
    baseline_churn = np.array([0.25, 0.18, 0.12, 0.08, 0.06, 0.05])
    baseline_curvature = np.array([0.70, 0.55, 0.45, 0.40, 0.38, 0.36])

    # Simulated HHC data (reduced churn/curvature at boundaries)
    hhc_churn = np.array([0.15, 0.12, 0.09, 0.07, 0.06, 0.05])
    hhc_curvature = np.array([0.50, 0.45, 0.42, 0.39, 0.37, 0.36])

    # Style settings
    baseline_style = {
        "color": "#1f77b4",
        "linestyle": "--",
        "marker": "o",
        "markersize": 6,
        "linewidth": 1.5,
        "label": "Baseline",
    }
    hhc_style = {
        "color": "#ff7f0e",
        "linestyle": "-",
        "marker": "s",
        "markersize": 6,
        "linewidth": 2,
        "label": "HHC",
    }

    # Left subplot: Token churn rate
    ax1.plot(distance_bins, baseline_churn, **baseline_style)
    ax1.plot(distance_bins, hhc_churn, **hhc_style)

    ax1.set_xlabel("Distance from boundary (bytes)", fontsize=11)
    ax1.set_ylabel("Token churn rate", fontsize=11)
    ax1.set_title("(a) Token Churn vs Distance", fontsize=12)
    ax1.legend(loc="upper right", frameon=True, framealpha=0.9)
    ax1.grid(True, alpha=0.3, linestyle="-", linewidth=0.5)
    ax1.set_xlim(left=-5)
    ax1.set_ylim(bottom=0, top=0.30)

    # Right subplot: Curvature
    ax2.plot(distance_bins, baseline_curvature, **baseline_style)
    ax2.plot(distance_bins, hhc_curvature, **hhc_style)

    ax2.set_xlabel("Distance from boundary (bytes)", fontsize=11)
    ax2.set_ylabel("Curvature", fontsize=11)
    ax2.set_title("(b) Curvature vs Distance", fontsize=12)
    ax2.legend(loc="upper right", frameon=True, framealpha=0.9)
    ax2.grid(True, alpha=0.3, linestyle="-", linewidth=0.5)
    ax2.set_xlim(left=-5)
    ax2.set_ylim(bottom=0.30, top=0.75)

    # Adjust layout
    plt.tight_layout()

    # Save figure
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=300, bbox_inches="tight", format="pdf")
    plt.close(fig)

    print(f"Simulated figure saved to {output_path}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate boundary analysis figure for HHC stability paper",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # Generate from default data location
    uv run scripts/generate_boundary_figure.py

    # Generate from specific input file
    uv run scripts/generate_boundary_figure.py --input eval/results/hhc/boundary_figure_data.json

    # Generate to specific output location
    uv run scripts/generate_boundary_figure.py --output paper/figures/boundary_analysis.pdf

    # Generate placeholder figure (no input data required)
    uv run scripts/generate_boundary_figure.py --placeholder
        """,
    )

    parser.add_argument(
        "--input",
        type=Path,
        default=Path("eval/results/boundary_figure_data.json"),
        help="Path to boundary_figure_data.json (default: eval/results/boundary_figure_data.json)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("paper/figures/boundary_analysis.pdf"),
        help="Output path for PDF figure (default: paper/figures/boundary_analysis.pdf)",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=300,
        help="DPI for raster elements (default: 300)",
    )
    parser.add_argument(
        "--placeholder",
        action="store_true",
        help="Generate a placeholder figure with simulated data",
    )

    args = parser.parse_args()

    if args.placeholder:
        create_simulated_figure(args.output)
        return

    # Try to load data from input file
    if args.input.exists():
        print(f"Loading data from {args.input}")
        data = load_figure_data(args.input)
        create_boundary_figure(data, args.output, dpi=args.dpi)
    else:
        print(f"Input file not found: {args.input}")
        print("Creating simulated figure instead...")
        print("Run `uv run scripts/report.py --compare <baseline> <hhc>` to generate actual data.")
        create_simulated_figure(args.output)


if __name__ == "__main__":
    main()
